// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWIMSsEy4e7dBwLt5_b0fzLE2MwfJyyuc',
    appId: '1:128192313521:web:edbf5c703a8b8115a08a90',
    messagingSenderId: '128192313521',
    projectId: 'rd-user-management-cd',
    authDomain: 'rd-user-management-cd.firebaseapp.com',
    databaseURL: 'https://rd-user-management-cd-default-rtdb.firebaseio.com',
    storageBucket: 'rd-user-management-cd.firebasestorage.app',
    measurementId: 'G-MJMKZ9N0QY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOAM30-QXrKc1Yk5CsV3LdNpqIKOkJTYM',
    appId: '1:128192313521:android:92fa6fc752919a4fa08a90',
    messagingSenderId: '128192313521',
    projectId: 'rd-user-management-cd',
    databaseURL: 'https://rd-user-management-cd-default-rtdb.firebaseio.com',
    storageBucket: 'rd-user-management-cd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYAJwZlPes9b23DA6ff1sT0gciSg6FYi8',
    appId: '1:128192313521:ios:f044d00cf4b0f0d7a08a90',
    messagingSenderId: '128192313521',
    projectId: 'rd-user-management-cd',
    databaseURL: 'https://rd-user-management-cd-default-rtdb.firebaseio.com',
    storageBucket: 'rd-user-management-cd.firebasestorage.app',
    iosBundleId: 'com.rodacd.rdUserCd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYAJwZlPes9b23DA6ff1sT0gciSg6FYi8',
    appId: '1:128192313521:ios:f044d00cf4b0f0d7a08a90',
    messagingSenderId: '128192313521',
    projectId: 'rd-user-management-cd',
    databaseURL: 'https://rd-user-management-cd-default-rtdb.firebaseio.com',
    storageBucket: 'rd-user-management-cd.firebasestorage.app',
    iosBundleId: 'com.rodacd.rdUserCd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWIMSsEy4e7dBwLt5_b0fzLE2MwfJyyuc',
    appId: '1:128192313521:web:2e9b2c7ea33ba498a08a90',
    messagingSenderId: '128192313521',
    projectId: 'rd-user-management-cd',
    authDomain: 'rd-user-management-cd.firebaseapp.com',
    databaseURL: 'https://rd-user-management-cd-default-rtdb.firebaseio.com',
    storageBucket: 'rd-user-management-cd.firebasestorage.app',
    measurementId: 'G-50GKQT1B7Z',
  );

}